#! /usr/bin/env bash

# Watch paths and restart <command> on detected changes
# Usage: runner <command> <path1> ...

command="$1"
shift

stop() {
    pids="$(
        pstree -p ${1:?Need pid} |
        sed -e 's/---/\n/g' | # sed won't parse newly created lines as separate input !
        sed -e 's/[^\(]*[\(]//g' -e 's/[\)]$//g'
    )"

    if [ -n "${pids}" ]
    then
        echo "Stopping" $pids >&2
        kill $pids
    fi
}

if [ "${#@}" -lt 1 ]
then
    echo "No filename(s) provided for monitoring"
    exit 225
fi

trap "echo 'Stopped by user'; run=false" 1 2 3 15

run=true pid= previous_hash= && while $run
do
    new_hash=$(for path in $@; do find "${path}" -ls; done | md5sum)

    if [ "${previous_hash}" != "${new_hash}" ]
    then
        if [ -n "${pid}" -a -d /proc/${pid} ]
        then
            stop ${pid}
            sleep 2
            pid=
        fi

        bash -c "${command}" & pid=$!
        echo "(re)started as pid ${pid} after hash change" >&2
    fi

    previous_hash="${new_hash}"
    sleep 15
done

echo "Exited after user interruption" >&2

if [ -n "${pid}" -a -d /proc/${pid} ]
then
    stop ${pid}
fi
